chore: update WPT expectations
GoogleChromeLabs/chromium-bidi pull request #1121
Opened 2023-08-01 11:12 UTC by jrandolf

2023-08-01 12:54 UTC, Lightning00Blade approved these changes

2023-08-02 12:09 UTC, thiagowfx approved these changes

2023-08-02 12:09 UTC, thiagowfx requested changes
There's some `sharedId` error.

2023-08-20 20:23 UTC, thiagowfx commented
This is obsolete, right? Can we close it?

2023-08-20 20:35 UTC, closed without merging