chore: use local EsLint/Prettier for hook
GoogleChromeLabs/chromium-bidi pull request #1464
Opened 2023-10-20 14:13 UTC by Lightning00Blade

Note: wait for all test to pass + Puppeteer run, before merging.

2023-10-20 14:15 UTC, thiagowfx commented on .eslintrc.js
> +    // This is more performant; see https://v8.dev/blog/fast-async.
please add this comment to the right side of the rule, so that keep-sorted is happy

2023-10-20 14:17 UTC, thiagowfx commented on .pre-commit-config.yaml
The pre-commit change seems unrelated.

We don't use `local` so that pre-commit is reproducible (always installing the same fixed version). Different people may have different versions of prettier installed locally due to different OSes and package managers (e.g. npm, homebrew, apt, etc).

Can you revert this part?

2023-10-20 14:30 UTC, Lightning00Blade commented on .pre-commit-config.yaml
Why is this not reproducible if we have a `package-lock.json`, `npx` run the first `node_module/bin` ?
This way we have a single dependency and not 2 that can become out of sync. 
Also I am not sure currently it works correctly as in the mirror you are told you need to define `additional_dependencies` https://github.com/pre-commit/mirrors-eslint. 
And this pre-hook never auto-formats.

2023-10-20 15:40 UTC, thiagowfx commented on .pre-commit-config.yaml
> +  - repo: local
In fact, even `id: copyright` could be consolidated here.

2023-10-23 09:20 UTC, thiagowfx approved these changes

2023-10-23 09:30 UTC, thiagowfx commented on .pre-commit-config.yaml
> +      - id: eslint
eslint -> prettier

2023-10-23 09:30 UTC, thiagowfx requested changes
See open comment

2023-10-23 09:43 UTC, thiagowfx approved these changes

2023-10-23 11:58 UTC, merged